apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: my-ns
  labels:
    app: multi-container-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 6379
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
