apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: my-ns
  labels:
    app: multi-container-app
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["/bin/bash","-c","while true;do echo c1;sleep 5;done"]
      
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["/bin/bash","-c","while true;do echo c1;sleep 5;done"]
     
